# version: '3.8'

services:
  seguridad:
    build: ./seguridad
    networks:
      - app_network

  usuarios:
    build: ./usuarios
    depends_on:
      - seguridad
    networks:
      - app_network
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - usuarios
        - seguridad
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
